### ISSUE TITLE
Plot the Coordinates on the Videos

### ISSUE THREAD

**Issue by nit29sin** [ddetommaso/TobiiGlassesPySuite#8]
Thank you for your help on the previous issue.
Can this library be used to plot the Coordinates given in livedata.json.gz file on the videos?

**Comment by ddetommaso** [comment]
Hi @nit29sin 

the following example shows how to play a recording with mapped gaze.

https://github.com/ddetommaso/TobiiGlassesPySuite-Examples/blob/master/live/replay.py

Hope you can find it useful!
